project:
  type: website
  output-dir: docs

website: 
  title: "IRC Latin America"
  navbar: 
    left: 
      - text: "Client reach"
        href: index.qmd
  
execute:
  freeze: auto   # optional: only re-render if source changes
  echo: false

format:
  html: 
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    number-sections: false
    navbar:
      background: white
      foreground: black