project:
  type: website
  output-dir: docs

website: 
  title: |
    <a href="https://www.rescue.org" class="brand-logo">
      <img src="images/irc_logo.jpg" alt="IRC Logo">
    </a>
  navbar: 
    left: 
      - text: "Latin America client reach"
        href: index.qmd
  
execute:
  freeze: auto   # optional: only re-render if source changes
  echo: false

format:
  html: 
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    number-sections: false
    navbar:
      background: white
      foreground: black